on:
  push:
    branches:
      - dev
  workflow_dispatch:

name: dev CITATION.cff
jobs:
  Validate-dev-CITATION-cff:
    runs-on: ubuntu-latest
    name: Validate CITATION.cff
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
          
      - name: Validate ./examples/key-complete/CITATION.cff
        uses: dieghernan/cff-validator@main
        with:
          citation-path: "./examples/key-complete/CITATION.cff"
        
      - name: Validate ./examples/key-error/CITATION.cff
        uses: dieghernan/cff-validator@main
        with:
          citation-path: "./examples/key-error/CITATION.cff"
          