on:
  push:
    paths:
      - examples/key-error/CITATION.cff
      - action.yml
    workflow_dispatch:

name: CITATION.cff-error
jobs:
  Validate-CITATION-cff-error:
    runs-on: macos-latest
    name: Validate CITATION.cff
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Validate examples/key-error/CITATION.cff
        uses: dieghernan/cff-validator@main
        with:
          citation-path: "./examples/key-error/CITATION.cff"

