on:
  push:
    paths:
      - examples/key-complete/CITATION.cff
      - action.yml
    workflow_dispatch:

name: CITATION.cff-complete
jobs:
  Validate-CITATION-cff-complete:
    runs-on: ubuntu-latest
    name: Validate CITATION.cff
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      RSPM: "https://packagemanager.rstudio.com/cran/__linux__/focal/latest"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # This is needed for workflows running on
      # ubuntu-20.04 or later
      - name: Install V8
        if: runner.os == 'Linux'
        run: |
          sudo apt-get install -y libv8-dev

      - name: Validate examples/key-complete/CITATION.cff
        uses: dieghernan/cff-validator@main
        with:
          citation-path: "./examples/key-complete/CITATION.cff"

      # Upload artifact
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: citation-cff-errors
          path: citation_cff_errors.md
