on:
  push:
    branches:
      - dev
    workflow_dispatch:

name: dev CITATION.cff
jobs:
  Validate-dev-CITATION-cff:
    runs-on: ubuntu-latest
    name: Validate CITATION.cff
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      RSPM: "https://packagemanager.rstudio.com/cran/__linux__/focal/latest"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # This is needed for workflows running on
      # ubuntu-20.04 or later
      - name: Install V8
        if: runner.os == 'Linux'
        run: |
          sudo apt-get install -y libv8-dev
          
      - name: Validate CITATION_full.cff
        uses: dieghernan/cff-validator@dev
        with:
          citation-path: "examples/CITATION_full.cff"
        
      #- name: Validate examples/CITATION_error.cff
      #  uses: dieghernan/cff-validator@dev
      #  with:
      #    citation-path: "examples/CITATION_error.cff"
          
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: citation-cff-errors
          path: citation_cff_errors.md
